# Generated by Django 4.2.6 on 2023-11-29 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inf_animales',
            fields=[
                ('id_inf', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('habitad', models.CharField(max_length=100)),
                ('resumen', models.CharField(max_length=300)),
                ('informacion', models.CharField(max_length=500)),
                ('imagen', models.CharField(max_length=150)),
                ('created_by_2', models.IntegerField()),
            ],
            options={
                'db_table': 'inf_animales',
                'managed': False,
            },
        ),
    ]
