# Generated by Django 4.2.4 on 2023-11-11 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inf_animales',
            fields=[
                ('id_inf', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45, unique=True)),
                ('region', models.CharField(max_length=45)),
                ('texto', models.CharField(max_length=300)),
                ('created_by_2', models.IntegerField()),
            ],
            options={
                'db_table': 'inf_animales',
                'managed': False,
            },
        ),
    ]
