# Generated by Django 4.2.6 on 2023-11-25 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(help_text='(Favor pegar desde el portapapeles)', max_length=140)),
                ('contenidos', models.CharField(help_text='Explique que vió en su avistamiento', max_length=1500)),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
