# Generated by Django 4.2.6 on 2023-12-05 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0002_comentario_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='foto',
        ),
        migrations.AddField(
            model_name='comentario',
            name='ubicacion',
            field=models.CharField(default='[-36.552302, -71.889792]', help_text='(Favor pegar sin cambios desde el portapapeles)', max_length=140),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comentario',
            name='contenido',
            field=models.CharField(help_text='Explique que ocurrió en su avistamiento', max_length=21381),
        ),
    ]
